apiVersion: v1
kind: Service
metadata:
  name: predictor-model-service
spec:
  type: NodePort  # Use NodePort to expose the service on a port on each node
  selector:
    app: predictor-model  # This should match the labels of your deployment
  ports:
    - port: 80           # Port that the service will expose
      targetPort: 8000     # Port on the container
      nodePort: 30080    # Optional: specify a node port (between 30000-32767)

      
